# Generated by Django 3.2.18 on 2023-05-03 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('javascript', 'JavaScript'), ('python', 'Python'), ('java', 'Java'), ('c++', 'C++'), ('c#', 'C#'), ('typescript', 'TypeScript'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('go', 'Go'), ('kotlin', 'Kotlin'), ('rust', 'Rust'), ('php', 'PHP'), ('perl', 'Perl'), ('html', 'HTML'), ('css', 'CSS'), ('other', 'Other')], max_length=25)),
                ('confidence', models.CharField(blank=True, choices=[('1', 'Novice'), ('2', 'Advanced Beginner'), ('3', 'Competent'), ('4', 'Proficient'), ('5', 'Expert')], max_length=25)),
                ('used_since', models.DateField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
    ]
