# Generated by Django 3.2.18 on 2023-05-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_content_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='profile_name',
        ),
    ]
