# Generated by Django 3.2.18 on 2023-05-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='github_link',
            field=models.URLField(blank=True),
        ),
    ]
