# Generated by Django 3.2.18 on 2023-05-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_primary_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='primary_language',
            field=models.CharField(blank=True, choices=[('javascript', 'JavaScript'), ('python', 'Python'), ('java', 'Java'), ('c++', 'C++'), ('c#', 'C#'), ('typescript', 'TypeScript'), ('ruby', 'Ruby'), ('swift', 'Swift'), ('go', 'Go'), ('kotlin', 'Kotlin'), ('rust', 'Rust'), ('php', 'PHP'), ('perl', 'Perl'), ('html', 'HTML'), ('css', 'CSS'), ('other', 'Other')], max_length=25),
        ),
    ]
